# Generated by Django 3.1.5 on 2021-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0005_auto_20210531_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='fb_app.Profile'),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
