# Generated by Django 3.1.5 on 2021-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0011_auto_20210602_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
